### ISSUE TITLE
Access to HTTP headers

### ISSUE THREAD

**Issue by PhilippMi** [akre54/Backbone.NativeAjax#8]
We recently switched from jQuery to NativeView/NativeAjax. Before the switch I was able to access the HTTP headers through the XHR object in my Backbone `parse` method:

    parse(response, options) {
        if (options.xhr.getResponseHeader('Content-Type').includes('application/vnd.api+json')) {
            ...
        }
    }

With NativeAjax, `options.xhr` is a Promise which resolves to the data I already have through the `response` parameter.

Hence, I have no possibility to access the response headers or did I miss something?

_Backbone: 1.2.1_
_Backbone.NativeAjax: 0.3.2_

**Comment by akre54** [comment]
Yes, Backbone [assigns options.xhr](https://github.com/jashkenas/backbone/blob/1.2.1/backbone.js#L1390) to the return value of `Backbone.ajax` because the return value from `$.ajax` is a [jqXHR](http://api.jquery.com/jQuery.ajax/#jqXHR), basically an XHR wrapped in a $.Deferred. It's similar but not exactly what we do here.

We have a few options here:

1. We could provide an `originalXhr` property on the `options` object ourselves.
2. We could assign a `xhr` property on the returned promise that you could access as `options.xhr.xhr`. 
3. We could emulate jqXHR by proxying `readyState`, `status`, `getAllResponseHeaders`, etc. from xhr on the returned promise.

I'd prefer to be able to access the real original xhr if needed, but I prefer the API of using those methods directly on the returned promise. Let me see what I can come up with.

**Comment by akre54** [comment]
Try 44f0df0 and see if that works for you.

**Comment by PhilippMi** [comment]
Works great! Thanks for the quick fix.

**Comment by akre54** [comment]
One sec.. just realized I have to update the promise methods in `onreadystatechange`. Patch incoming.
